# -*- coding: utf-8 -*-
"""ds380 analyses

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16yZtCWsL4rX7BfYGPNCUlgkYKBjzlijA
"""

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rcParams['figure.dpi']= 75  # set the resolution of displayed figures
mpl.rc("savefig", dpi=150) # set the resolution of saved figures
plt.style.use('seaborn-v0_8')

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/boston_crime_data.csv', delimiter=',')
df.head()

df = pd.read_csv('/content/drive/MyDrive/boston_crime_data.csv', delimiter=',')
df

total_districts = df['DISTRICT'].unique()
print("Districts featured in the dataset:", total_districts)

#this code features all of the unique districts featured in the dataset

mode_dist = df['DISTRICT'].mode()[0] #denoting the most frequently appearing district
print("most frequently appearing area code", mode_dist)

top_five_dist = df['DISTRICT'].value_counts()  # count occurrences
print(f"the top five crime-laden area codes and their number of occurrences: {top_five_dist.head(5)}")

plt.figure(figsize=(8, 6))
plt.pie(top_five_dist.values, labels=top_five_dist.index, autopct='%1.1f%%')
plt.title('Distribution of Crimes Across the Top 5 Most Reported Districts')
plt.show()

d4_count = df['DISTRICT'].value_counts().get('D4')
total_crimes = len(df)

d4_ratio = d4_count / total_crimes
d4_percentage = d4_ratio * 100

print("this is the percentage of the number of crimes in the D4 district compared to the rest of the dataset:", d4_percentage)

district_crime_counts = df['DISTRICT'].value_counts()
district_crime_counts.plot(kind='bar', figsize=(10, 6), color='b')
plt.title('Number of Crimes by District')
plt.xlabel('District Code')
plt.ylabel('No. of Crimes')
plt.show()